language:
  - generic

services:
  - docker

env:
  global:
    - IMAGE_NAME=flask

before_install:
  - docker image build -t "$DOCKERUSER"/"$IMAGE_NAME" .

before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"

deploy:
  provider: script
  script: docker image push "$DOCKERUSER"/"$IMAGE_NAME"
  on:
    branch: main
